services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: skarbnyk
      POSTGRES_USER: skarbnyk
      POSTGRES_PASSWORD: skarbnyk
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
